name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the learning NODEJS project, basically I start this project for learning purposes at start. 
        Now I trying add best practices. Anyhow if you need any help or want to contribute you are welcome. 
        you can reach out to me on `mutti.mughal@gmail.com`"
        pr-message: "Please provide clear description/intention of the PR and assign author as reviewer for PR"
